name: Slack alert for dev branch

on:
  push:
    branches:
      - main
      - dev
      - 'feature/*'

  pull_request:
    branches:
      - main
      - dev
      - 'feature/*'

jobs:
  send-slack-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
