name: Slack alert for dev branch

on:
  push:
    branches:
      - main
      - dev
      - feature/*

  pull_request:
    branches:
      - main
      - dev
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Integration Test # default: 8398a7@action-slack
          fields: repo,commit,message,author # default: repo,commit
          mention: here
          if_mention: failure,cancelled
        env:
<<<<<<< HEAD
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_URL  }} # required
        if: always()
=======
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
>>>>>>> 839e9225126652cc1fd26663447dc12523e0dd50
